### PR TITLE
[hrpsys_ros_bridge_tutorials] Add custom head urdf (multisense cut)

### PR DESCRIPTION
**Pull request by wkentaro**
This is rviz config for audience in DRC in June 2015.
The model was provided by @kozuki and @yuki-asano .

image

### CODE REVIEW

**Comment by wkentaro** [comment]
**PLEASE DON'T MERGE THIS**
This may be temporary change.

**Comment by wkentaro** [comment]
cc: @k-okada

**Comment by wkentaro** [comment]
Please merge this to use this in OCS PCs.

**Comment by k-okada** [comment]
@snozawa @YoheiKakiuchi これ、HRP2のmass/inertia が入っていてダメじゃない？
commit を消して push -f するけど、大丈夫かな．

**Pull request merged**
