### PR TITLE
[test_hrpsys_samplerobot.launch] run start_omninames.sh for rostest

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by k-okada** [comment]
fails with this, release new version of rtmros_common should fix this
```
start testing [test-robot-init]
[ERROR] [1428666073.053061543]: Could not find roseus messages for pr2_msgs under (/home/travis/ros/ws_rtmros_tutorials/devel/share/roseus/ros /home/travis/ros/ws_rtmros_tutorials/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh pr2_msgs
[ERROR] [1428666073.053204011]: Could not find nil/manifest.l
try rosrun roseus generate-all-msg-srv.sh pr2_msgs
[ERROR] [1428666073.063059254]: Could not find roseus messages for pr2_controllers_msgs under (/home/travis/ros/ws_rtmros_tutorials/devel/share/roseus/ros /home/travis/ros/ws_rtmros_tutorials/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh pr2_controllers_msgs
[ERROR] [1428666073.063136594]: Could not find nil/manifest.l
try rosrun roseus generate-all-msg-srv.sh pr2_controllers_msgs
[ERROR] [1428666073.063249048]: Could not find roseus messages for control_msgs under (/home/travis/ros/ws_rtmros_tutorials/devel/share/roseus/ros /home/travis/ros/ws_rtmros_tutorials/devel/share/roseus/ros /opt/ros/hydro/share/roseus/ros)
try rosrun roseus generate-all-msg-srv.sh control_msgs
[ERROR] [1428666073.063289504]: Could not find nil/manifest.l
try rosrun roseus generate-all-msg-srv.sh control_msgs
/opt/ros/hydro/share/euslisp/jskeus/eus/Linux64/bin/irteusgl unittest-error: no such package CONTROL_MSGS in (apply #'ros::load-org-for-ros ros::fullname args), exitting...
[ERROR] test (apply #'ros::load-org-for-ros ros::fullname args) failed ... (no such package 45).
[ INFO] [1428666073.355365721, 46.600000000]: [HrpsysSeqStateROSBridge0] @onExecutece 0 is working at 202[Hz]
[rtmlaunch] Catch signal 'SIGINT', exitting...
```

**Comment by snozawa** [comment]
https://github.com/start-jsk/rtmros_tutorials/pull/235#issuecomment-91534541
Is this already fixed?

**Comment by k-okada** [comment]
Not yet, I'm about it release that

**Comment by k-okada** [comment]
but it seems https://travis-ci.org/start-jsk/rtmros_tutorials/builds/57936501 pass all test without releasing new version of rtmros_common

**Comment by snozawa** [comment]
In travis log, rostest does not executed.
```
  /opt/ros/hydro/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hrpsys_ros_bridge_tutorials --package=hrpsys_ros_bridge_tutorials --results-filename test_test_hrpsys_pa10.xml /home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hrpsys_ros_bridge_tutorials/test/test_hrpsys_pa10.launch 

Another rostest instance is currently running, waiting until it finished...

... logging to /home/travis/.ros/log/rostest-testing-worker-linux-e7a62211-2-2367-linux-3-57936502-31278.log

Traceback (most recent call last):

  File "/opt/ros/hydro/share/rostest/cmake/../../../bin/rostest", line 53, in <module>

    rostestmain()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain

    _main()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/rostest_main.py", line 142, in rostestmain

    testCase = rostest.runner.createUnitTest(pkg, test_file)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/rostest/runner.py", line 227, in createUnitTest

    config = roslaunch.parent.load_config_default([test_file], _DEFAULT_TEST_PORT)

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/config.py", line 430, in load_config_default

    raise RLException(e)

roslaunch.core.RLException: Invalid <arg> tag: hrpsys_ros_bridge_tutorials

ROS path [0]=/opt/ros/hydro/share/ros

ROS path [1]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hironx_tutorialge_tutorials

ROS path [2]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hironx_tutorialge_tutorials

ROS path [3]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hrpsys_tutorials

ROS path [4]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/openhrp3_tutorials

ROS path [5]=/home/travis/ros/ws_rtmros_tutorials/src/rtmros_tutorials/hrpsys_gazebo_tutorials

ROS path [6]=/opt/ros/hydro/share

ROS path [7]=/opt/ros/hydro/stacks. 
```

**Pull request merged**
