### PR TITLE
[hrpsys_ros_bridge_tutorials] Ignore generated models

### PR DESCRIPTION
**Pull request by wkentaro**
It is annoying if there are too many untracking files generated by build at running `git status`.

### CODE REVIEW

**Comment by k-okada** [comment]
do you think we can write with some rules?, like '*.dae', instaed of writing all files in .gitigure

**Comment by wkentaro** [comment]
`*.dae` seems fine, but there is already `*.urdf` files, so it demands additional rules.
The current declaration is based on a blacklist rule, and if we use whitelist rule, the lines of .gitignore will be short.
But user will need to declare .urdf file in .gitignore to add a new file to commit every times.
Below is the white list example.

```
*.dae
*.urdf

# white list
!HRP2JSKNTS_body_customHEAD.urdf
!HRP2JSKNTS_customHEAD.urdf
```

I thought this is not friendly for users who are not familiar with git, and they will say "`git add` not work! Why I can't stage it to commit?".

**Comment by k-okada** [comment]
It may surprising for you , but someone do not care about .gitignore, or
even they do not like that.
https://github.com/jsk-ros-pkg/trans_system/pull/49#issuecomment-74263087,
(and sadly two people who liked .gitignore not longer using this package
and people who like this have to keep maintain this,
 also we can find another one take care about .gitignore
https://github.com/jsk-ros-pkg/trans_system/commits/master/projects/trans_vm/.gitignore

 this thread is very insightful..)

so question is; are you ok with add new blacklist everytime someone add a
new robot?
or do you want to answer git add question? and since adding new urdf is not
welcomed, basically we should convert from wrl (at least I believe so)
so in that case you can answer "adding new urdf is not a good thing, try to
convince @k-okada about why you need this)'

So if I ware you, I'll chose white list, but if you are ok with blacklist,
I'll merge this (but maybe most of user do not like this ....)



--
◉ Kei Okada

**Comment by wkentaro** [comment]
Thanks for the comments. I think the whilte listing is better. Fixed.

**Pull request merged**
