### PR TITLE
fix travis

### PR DESCRIPTION
**Pull request by Naoki-Hiraoka**

### CODE REVIEW

**Comment by Naoki-Hiraoka** [comment]
関連　https://github.com/start-jsk/rtmros_tutorials/pull/602#issuecomment-984642222

**Review by kirohy — APPROVED** [review]
collada_robotsは使われていないのでこれでいいと思います

**Comment by Naoki-Hiraoka** [comment]
@k-okada こちらもmergeをお願いします．

**Comment by k-okada** [comment]
collada robots used in some examples https://github.com/start-jsk/rtmros_tutorials/search?q=collada_robots, so I have catkinzed https://sourceforge.net/p/jsk-ros-pkg/code/6097/ with https://github.com/ros-infrastructure/catkinize

**Comment by Naoki-Hiraoka** [comment]
@k-okada catkin対応ありがとうございます．collada_robotsを入れてテストが通りました．

**Pull request merged**
