### PR TITLE
[hrpsys_ros_bridge_tutorials] Euslisp interface of HIRONXJSK for latest hrpsys

### PR DESCRIPTION
**Pull request by pazeshun**
Depends on https://github.com/start-jsk/rtmros_hrp2/pull/507
Updated version of #549 

Thanks to updating hrpsys inside HIRONXJSK (see https://github.com/fkanehiro/hrpsys-base/pull/1283), we can delete special code for old hrpsys.

### CODE REVIEW

**Comment by pazeshun** [comment]
@Affonso-Gui Could you add document to hand interface methods?

**Comment by Affonso-Gui** [comment]
@pazeshun Created PR at https://github.com/pazeshun/rtmros_tutorials/pull/3

**Comment by pazeshun** [comment]
> @pazeshun Created PR at [pazeshun#3](https://github.com/pazeshun/rtmros_tutorials/pull/3)

Thanks. Merged.

**Comment by pazeshun** [comment]
https://github.com/start-jsk/rtmros_hrp2/pull/507 is already merged.
No more wait for upstream.

**Comment by pazeshun** [comment]
@YoheiKakiuchi Could you review & merge this?

**Comment by pazeshun** [comment]
@YoheiKakiuchi Kindly ping

**Comment by pazeshun** [comment]
@YoheiKakiuchi Kindly ping

**Comment by pazeshun** [comment]
@YoheiKakiuchi Kindly ping

**Comment by YoheiKakiuchi** [comment]
@k-okada Please merge this PR

**Comment by pazeshun** [comment]
@k-okada Could you merge this?
Sorry for rushing you, but this PR is required for online one-week project.

**Comment by pazeshun** [comment]
@k-okada kindly ping

**Comment by pazeshun** [comment]
@k-okada kindly ping

**Comment by pazeshun** [comment]
Thank you!!!

**Pull request merged**
